對萬用字元的一些修改
rime/rime-array pull request #8
Opened 2022-11-12 13:59 UTC by jeang-bo-yuan

更改內容
1. 修正萬用字元不能用在四碼罕字的Bug
2. 修改array30_query中拼寫運算的規則，以加快部署的速度
3. 萬用字元可以反查完整字碼，且每一個字碼皆以方括號框住，以增加可讀性

2022-11-14 16:41 UTC, archerindigo commented
感謝，我這幾天找空看看

2022-11-18 23:13 UTC, archerindigo requested changes
稍作了檢查，這個regex的運用很不錯。借用相同`()?`的概念可以將二、三碼萬用字元都混在一起，減少掃描derive的次數。建議修改如下：

```
  algebra:
    - xform/^(.*)!$/$1/                 # 簡碼
    - xform/^(.*)@$/$1/                 # 特別碼（須置於簡碼之後）
    # "?"萬用字元
    - derive/^([^?])([^?])?([^?])?[^?](i)?$/$1$2$3\?$4/   # .(.)(.)?(i)
    - derive/^([^?])([^?])[^?]([^?])(i)?$/$1$2\?$3$4/     # ..?.(i)
    - derive/^([^?])([^?])?[^?][^?](i)?$/$1$2\?\?$3/      # .(.)??(i)
    - derive/^([^?])[^?]([^?])([^?])?(i)?$/$1\?$2$3$4/    # .?.(.)(i)
    - derive/^([^?])[^?]([^?])[^?](i)?$/$1\?$2\?$3/       # .?.?(i)
    - derive/^([^?])[^?][^?]([^?])(i)?$/$1\?\?$2$3/       # .??.(i)
    - derive/^([^?])[^?][^?][^?](i)?$/$1\?\?\?$2/         # .???(i)
    - derive/^[^?]([^?])([^?])?([^?])?(i)?$/\?$1$2$3$4/   # ?.(.)(.)(i)
    - derive/^[^?]([^?])([^?])?[^?](i)?$/\?$1$2\?$3/      # ?.(.)?(i)
    - derive/^[^?]([^?])[^?]([^?])(i)?$/\?$1\?$2$3/       # ?.?.(i)
    - derive/^[^?]([^?])[^?][^?](i)?$/\?$1\?\?$2/         # ?.??(i)
    - derive/^[^?][^?]([^?])([^?])?(i)?$/\?\?$1$2$3/      # ??.(.)(i)
    - derive/^[^?][^?]([^?])[^?](i)?$/\?\?$1\?$2/         # ??.?(i)
    - derive/^[^?][^?][^?]([^?])(i)?$/\?\?\?$1$2/         # ???.(i)
```

2022-11-19 05:49 UTC, LEOYoon-Tsaw commented
這麼多derive，不會卡嗎

2022-11-19 06:37 UTC, jeang-bo-yuan commented
> 稍作了檢查，這個regex的運用很不錯。借用相同`()?`的概念可以將二、三碼萬用字元都混在一起，減少掃描derive的次數。建議修改如下：
> （……下略）

這構思挺不錯的，拼寫運算也看起來比較簡潔，已commit。

2022-11-19 06:41 UTC, jeang-bo-yuan commented
> 這麼多derive，不會卡嗎

部署時還是要等一段時間，打字時沒有明顯卡頓。不過在修改後，致少不會在性能較低的裝置上部署到當機。

2022-11-19 08:14 UTC, jeang-bo-yuan commented
@archerindigo 我剛才有在手機上測試了你提拱的修改方案，但好像是因為新的regex涵蓋的可能性太多了，所以不比原本那個簡單暴力的regex還要有效率。

我的手機在部署了修改後的方案後，Trime就一直當掉，因此我考慮將剛才的commit給revert。

2022-11-19 13:58 UTC, archerindigo commented
@jeang-bo-yuan 你指的當掉是有部署成功嗎？因為在我的手機上的Trime介面向來在部署各種比較大型的方案都會在部署完成一刻掛掉，不過部署其實還是成功的，所以沒有問題。

我也測試了在我這邊Trime部署的時間，每次測試前都將built內有關行列的檔案清空。發現修改regex後的版本會快一點點但分別不明顯：

|                   | Trime大約部署時間 (s) | array30_query.prism.bin大小 (MB) |
| ----------------- | --------------- | ------------------------------ |
| v2.0（pr前，無啟動萬用字元） | 6.5             | N/A                            |
| v2.0（pr前)         | 55              | 10.84                          |
| pr8（修改regex前）     | 21              | 22.13                          |
| pr8-2（修改regex後）   | 20              | 22.13                          |

使用上也是流暢，沒有感受到分別

就可讀性而言原來的暴力regex會好一點，最終採用哪種方式我沒有意見

2022-11-19 15:27 UTC, jeang-bo-yuan commented
@archerindigo 我剛才又測了一次，並且測了時間。因為我下午時用Trime 3.2.9版測到當掉，所以我也有將Trime降階到3.2.8版來測試：

|                      | 部署時間(s) | array30_query.prism.bin大小(MB) |
|---|---|---|
| (Trime 3.2.8) 修改regex前 | 50 | 22.1 |
| (Trime 3.2.8) 修改regex後 | 47 | 22.1 |
| (Trime 3.2.9) 修改regex前 | 50 | 22.1 |
| (Trime 3.2.9) 修改regex後 | 47 | 22.1 |

看起來修改regex後部署的較快。使用上流暢度沒什麼分別。

我下午測試「修改regex後」的版本時，原本是正常的，但之後修改了trime.yaml的內容後，Trime就一直停止運作。之後我一直嘗試在「修改regex前」和「修改regex後」的版本間切換，發現只有在「修改regex前」的版本Trime才能正常運作。

不過我剛才測試時，不論是用哪個版本都能順利運作，所以我猜應該是下午時遇到了奇怪的Bug才會導致Trime當掉。

2022-11-20 10:33 UTC, archerindigo commented
我沒有問題
@lotem 建議merge

2022-11-20 10:35 UTC, merged